
let quotes = [
    { q: "I do not fear computers. I fear lack of them.", p: "Isaac Asimov" },
    { q: "A computer once beat me at chess, but it was no match for me at kick boxing.", p: "Emo Philips" },
    { q: "Computer Science is no more about computers than astronomy is about telescopes.", p: "Edsger W. Dijkstra" },
    { q: "The computer was born to solve problems that did not exist before.", p: "Bill Gates" },
    { q: "Software is like entropy: It is difficult to grasp, weighs nothing, and obeys the Second Law of Thermodynamics; i.e., it always increases.", p: "Norman Augustine" },
    { q: "Software is a gas; it expands to fill its container.", p: "Nathan Myhrvold" },
    { q: "All parts should go together without forcing.  You must remember that the parts you are reassembling were disassembled by you.  Therefore, if you canвЂ™t get them together again, there must be a reason.  By all means, do not use a hammer.", p: "IBM Manual, 1925" },
    { q: "Standards are always out of date.  ThatвЂ™s what makes them standards.", p: "Alan Bennett" },
    { q: "Physics is the universeвЂ™s operating system.", p: "Steven R Garman" },
    { q: "ItвЂ™s hardware that makes a machine fast.  ItвЂ™s software that makes a fast machine slow.", p: "Craig Bruce" },
    { q: "Imagination is more important than knowledge.  For knowledge is limited, whereas imagination embraces the entire world, stimulating progress, giving birth to evolution.", p: "Albert Einstein" },
    { q: "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.", p: "Stephen Hawking" },
    { q: "The more you know, the more you realize you know nothing.", p: "Socrates" },
    { q: "Tell me and I forget.  Teach me and I remember.  Involve me and I learn.", p: "Benjamin Franklin" },
    { q: "Real knowledge is to know the extent of oneвЂ™s ignorance.", p: "Confucius" },
    { q: "If people never did silly things, nothing intelligent would ever get done.", p: "Ludwig Wittgenstein" },
    { q: "Getting information off the Internet is like taking a drink from a fire hydrant.", p: "Mitchell Kapor" },
    { q: "If you think your users are idiots, only idiots will use it.", p: "Linus Torvalds" },
    { q: "From a programmerвЂ™s point of view, the user is a peripheral that types when you issue a read request.", p: "P. Williams" },
    { q: "Where is the вЂanyвЂ™ key?", p: "Homer Simpson, in response to the message, вЂњPress any keyвЂќ" },
    { q: "Computers are good at following instructions, but not at reading your mind.", p: "Donald Knuth" },
    { q: "There is only one problem with common sense; itвЂ™s not very common.", p: "Milt Bryce" },
    { q: "Your most unhappy customers are your greatest source of learning.", p: "Bill Gates" },
    { q: "Let us change our traditional attitude to the construction of programs: Instead of imagining that our main task is to instruct a computer what to do, let us concentrate rather on explaining to human beings what we want a computer to do.", p: "Donald E. Knuth" },
    { q: "The Internet?  We are not interested in it.", p: "Bill Gates, 1993" },
    { q: "The best way to get accurate information on Usenet is to post something wrong and wait for corrections.", p: "Matthew Austern" },
    { q: "The most likely way for the world to be destroyed, most experts agree, is by accident.  ThatвЂ™s where we come in; weвЂ™re computer professionals.  We cause accidents.", p: "Nathaniel Borenstein" },
    { q: "Pessimists, weвЂ™re told, look at a glass containing 50% air and 50% water and see it as half empty.  Optimists, in contrast, see it as half full.  Engineers, of course, understand the glass is twice as big as it needs to be.", p: "Bob Lewis" },
    { q: "In a room full of top software designers, if two agree on the same thing, thatвЂ™s a majority.", p: "Bill Curtis" },
    { q: "It should be noted that no ethically-trained software engineer would ever consent to write a DestroyBaghdad procedure.  Basic professional ethics would instead require him to write a DestroyCity procedure, to which Baghdad could be given as a parameter.", p: "Nathaniel S. Borenstein" },
    { q: "Mostly, when you see programmers, they arenвЂ™t doing anything.  One of the attractive things about programmers is that you cannot tell whether or not they are working simply by looking at them.  Very often theyвЂ™re sitting there seemingly drinking coffee and gossiping, or just staring into space.  What the programmer is trying to do is get a handle on all the individual and unrelated ideas that are scampering around in his head.", p: "Charles M. Strauss" },
    { q: "If you think you are worth what you know, you are very wrong.  Your knowledge today does not have much value beyond a couple of years.  Your value is what you can learn and how easily you can adapt to the changes this profession brings so often.", p: "Jose M. Aguilar" },
    { q: "Programs must be written for people to read, and only incidentally for machines to execute.", p: "Abelson and Sussman" },
    { q: "Commenting your code is like cleaning your bathroom вЂ” you never want to do it, but it really does create a more pleasant experience for you and your guests.", p: "Ryan Campbell" },
    { q: "We have to stop optimizing for programmers and start optimizing for users.", p: "Jeff Atwood" },
    { q: "Low-level programming is good for the programmerвЂ™s soul.", p: "John Carmack" },
    { q: "ItвЂ™s OK to figure out murder mysteries, but you shouldnвЂ™t need to figure out code.  You should be able to read it.", p: "Steve McConnell" },
    { q: "If we wish to count lines of code, we should not regard them as вЂlines producedвЂ™ but as вЂlines spent.'", p: "Edsger Dijkstra" },
    { q: "Programming can be fun, so can cryptography; however they should not be combined.", p: "Kreitzberg and Shneiderman" },
    { q: "Before software should be reusable, it should be usable.", p: "Ralph Johnson" },
    { q: "If you automate a mess, you get an automated mess.", p: "Rod Michael" },
    { q: "Looking at code you wrote more than two weeks ago is like looking at code you are seeing for the first time.", p: "Dan Hurvitz" },
    { q: "It is easier to change the specification to fit the program than vice versa.", p: "Alan Perlis" },
    { q: "Less than 10% of the code has to do with the ostensible purpose of the system; the rest deals with input-output, data validation, data structure maintenance, and other housekeeping.", p: "Mary Shaw" },
    { q: "If you have a procedure with ten parameters, you probably missed some.", p: "Alan Perlis" },
    { q: "How rare it is that maintaining someone elseвЂ™s code is akin to entering a beautifully designed building, which you admire as you walk around and plan how to add a wing or do some redecorating. More often, maintaining someone elseвЂ™s code is like being thrown headlong into a big pile of slimy, smelly garbage.", p: "Bill Venners" },
    { q: "Code generation, like drinking alcohol, is good in moderation.", p: "Alex Lowe" },
    { q: "Simplicity, carried to the extreme, becomes elegance.", p: "Jon Franklin" },
    { q: "A program is never less than 90% complete, and never more than 95% complete.", p: "Terry Baker" },
    { q: "When you are stuck in a traffic jam with a Porsche, all you do is burn more gas in idle.  Scalability is about building wider roads, not about building faster cars.", p: "Steve Swartz" },
    { q: "Everyone by now presumably knows about the danger of premature optimization.  I think we should be just as worried about premature design вЂ” designing too early what a program should do.", p: "Paul Graham" },
    { q: "Programming without an overall architecture or design in mind is like exploring a cave with only a flashlight: You donвЂ™t know where youвЂ™ve been, you donвЂ™t know where youвЂ™re going, and you donвЂ™t know quite where you are.", p: "Danny Thorpe" },
    { q: "The best way to predict the future is to implement it.", p: "David Heinemeier Hansson" },
    { q: "We need above all to know about changes; no one wants or needs to be reminded 16 hours a day that his shoes are on.", p: "David Hubel" },
    { q: "On two occasions I have been asked, вЂIf you put into the machine wrong figures, will the right answers come out?вЂ™  I am not able rightly to apprehend the kind of confusion of ideas that could provoke such a question.", p: "Charles Babbage" },
    { q: "Make everything as simple as possible, but not simpler.", p: "Albert Einstein" },
    { q: "Today, most software exists, not to solve a problem, but to interface with other software.", p: "IO Angell" },
    { q: "Good specifications will always improve programmer productivity far better than any programming tool or technique.", p: "Milt Bryce" },
    { q: "The difference between theory and practice is that in theory, there is no difference between theory and practice.", p: "Richard Moore" },
    { q: "DonвЂ™t document the problem, fix it.", p: "Atli BjГ¶rgvin Oddsson" },
    { q: "As a rule, software systems do not work well until they have been used, and have failed repeatedly, in real applications.", p: "Dave Parnas" },
    { q: "If the code and the comments do not match, possibly both are incorrect.", p: "Norm Schryer" },
    { q: "I think itвЂ™s a new feature.  DonвЂ™t tell anyone it was an accident.", p: "Larry Wall" },
    { q: "If you donвЂ™t handle [exceptions], we shut your application down.  That dramatically increases the reliability of the system.", p: "Anders Hejlsberg" },
    { q: "When debugging, novices insert corrective code; experts remove defective code.", p: "Richard Pattis" },
    { q: "In a software project team of 10, there are probably 3 people who produce enough defects to make them net negative producers.", p: "Gordon Schulmeyer" },
    { q: "I think it is inevitable that people program poorly.  Training will not substantially help matters.  We have to learn to live with it.", p: "Alan Perlis" },
    { q: "Program testing can be a very effective way to show the presence of bugs, but is hopelessly inadequate for showing their absence.", p: "Edsger Dijkstra" },
    { q: "Manually managing blocks of memory in C is like juggling bars of soap in a prison shower: ItвЂ™s all fun and games until you forget about one of them.", p: "anonymous Usenet user" },
    { q: "ThereвЂ™s no obfuscated Perl contest because itвЂ™s pointless.", p: "Jeff Polk" },
    { q: "Java is the most distressing thing to hit computing since MS-DOS.", p: "Alan Kay" },
    { q: "There are only two things wrong with C++:  The initial concept and the implementation.", p: "Bertrand Meyer" },
    { q: "It was a joke, okay?  If we thought it would actually be used, we wouldnвЂ™t have written it!", p: "Mark Andreesen, speaking of the HTML tag BLINK" },
    { q: "Web Services are like teenage sex.  Everyone is talking about doing it, and those who are actually doing it are doing it badly.", p: "Michelle Bustamante" },
    { q: "Perl: The only language that looks the same before and after RSA encryption.", p: "Keith Bostic" },
    { q: "I didnвЂ™t work hard to make Ruby perfect for everyone, because you feel differently from me.  No language can be perfect for everyone.  I tried to make Ruby perfect for me, but maybe itвЂ™s not perfect for you.  The perfect language for Guido van Rossum is probably Python.", p: "Yukihiro Matsumoto, aka вЂњMatzвЂќ, creator of Ruby" },
    { q: "XML is not a language in the sense of a programming language any more than sketches on a napkin are a language.", p: "Charles Simonyi" },
    { q: "BASIC is to computer programming as QWERTY is to typing.", p: "Seymour Papert" },
    { q: "It has been discovered that C++ provides a remarkable facility for concealing the trivial details of a program вЂ” such as where its bugs are.", p: "David Keppel" },
    { q: "UNIX is simple.  It just takes a genius to understand its simplicity.", p: "Dennis Ritchie" },
    { q: "Some people, when confronted with a problem, think вЂI know, IвЂ™ll use regular expressions.вЂ™  Now they have two problems.", p: "Jamie Zawinski" },
    { q: "I think computer viruses should count as life.  I think it says something about human nature that the only form of life we have created so far is purely destructive.  WeвЂ™ve created life in our own image.", p: "Stephen Hawking" },
    { q: "The only truly secure system is one that is powered off, cast in a block of concrete and sealed in a lead-lined room with armed guards.", p: "Gene Spafford" },
    { q: "Being able to break security doesnвЂ™t make you a hacker anymore than being able to hotwire cars makes you an automotive engineer.", p: "Eric Raymond" },
    { q: "Companies spend millions of dollars on firewalls, encryption and secure access devices, and itвЂ™s money wasted, because none of these measures address the weakest link in the security chain.", p: "Kevin Mitnick" },
    { q: "If you think technology can solve your security problems, then you donвЂ™t understand the problems and you donвЂ™t understand the technology.", p: "Bruce Schneier" },
    { q: "Hoaxes use weaknesses in human behavior to ensure they are replicated and distributed.  In other words, hoaxes prey on the Human Operating System.", p: "Stewart Kirkpatrick" },
    { q: "Passwords are like underwear: you donвЂ™t let people see it, you should change it very often, and you shouldnвЂ™t share it with strangers.", p: "Chris Pirillo" },
    { q: "I am not out to destroy Microsoft, that would be a completely unintended side effect.", p: "Linus Torvalds" },
    { q: "Yes, we have a dress code. You have to dress.", p: "Scott McNealy, co-founder of Sun Microsystems" },
    { q: "In an information economy, the most valuable company assets drive themselves home every night.  If they are not treated well, they do not return the next morning.", p: "Peter Chang" },
    { q: "ItвЂ™s better to wait for a productive programmer to become available than it is to wait for the first available programmer to become productive.", p: "Steve McConnell" },
    { q: "IвЂ™m not one of those who think Bill Gates is the devil.  I simply suspect that if Microsoft ever met up with the devil, it wouldnвЂ™t need an interpreter.", p: "Nicholas Petreley" },
    { q: "Two years from now, spam will be solved.", p: "Bill Gates, 2004" },
    { q: "The problem of viruses is temporary and will be solved in two years.", p: "John McAfee, 1988" },
    { q: "Computer viruses are an urban legend.", p: "Peter Norton, 1988" },
    { q: "In 2031, lawyers will be commonly a part of most development teams.", p: "Grady Booch" },
    { q: "I donвЂ™t know what the language of the year 2000 will look like, but I know it will be called Fortran.", p: "CA Hoare, 1982" },
    { q: "In the future, computers may weigh no more than 1.5 tonnes.", p: "Popular mechanics, 1949" },
    { q: "I see little commercial potential for the Internet for at least ten years.", p: "Bill Gates, 1994" },
    { q: "Before man reaches the moon, mail will be delivered within hours from New York to California, to Britain, to India or Australia.", p: "Arthur Summerfield, 1959, United States Post" },
]

document.addEventListener("DOMContentLoaded", () => {
    let quote = quotes[Math.floor(Math.random() * quotes.length)];
    document.getElementById("quote").innerHTML = `&ldquo;${quote.q}&rdquo;`;
    document.getElementById("person").innerHTML = quote.p;
})